trigger: none

pool:
  vmImage: 'macOS-latest'

variables:
  - group: secrets
  - name: url
    value: 'YOUR_SERVER_DOMAIN_HERE/hooks'

steps:
  - task: RocketChatHookNotification@1
    inputs:
      hookUrl: '$(url)/$(serverTokenFromSecretsGroup)'
      message: 'New information available'

  - task: RocketChatHookNotification@1
    inputs:
      hookUrl: '$(url)/$(serverTokenFromSecretsGroup)'
      message: 'Check my last tweet!'
      username: 'Azure DevOps Bot' # Optional

  - task: RocketChatHookNotification@1
    inputs:
      hookUrl: '$(url)/$(serverTokenFromSecretsGroup)'
      message: 'Check my last tutorial!'
      username: 'BOT Infos' # Optional
      attachmentTitle: 'New website' # Optional
      attachmentTitleLink: 'https://www.url.com' # Optional

  - task: RocketChatHookNotification@1
    inputs:
      hookUrl: '$(url)/$(serverTokenFromSecretsGroup)'
      message: 'Check my last tweet!'
      username: 'BOT Infos' # Optional
      attachmentTitle: 'Twitter' # Optional
      attachmentTitleLink: 'https://www.twitter.com' # Optional
      attachmentText: 'This is for...' # Optional
      attachmentColor: '#00FF00' # Optional
      attachmentImageUrl: 'https://images.unsplash.com/photo-1611162618479-ee3d24aaef0b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1567&q=80' # Optional
